name: open_ai_anthropic
description: An anthropic client with OpenAI API Specs.

version: 0.1.0

environment:
  sdk: ^3.11.0

dependencies:
  meta: ">=1.17.0 <2.0.0"
  http: ">=1.4.0 <2.0.0"
  anthropic_sdk_dart: ^0.3.1
  openai_dart: ^0.6.2
  json_annotation: ">=4.8.0 <5.0.0"
  http_interceptor: ">=2.0.0 <3.0.0"
  universal_io: ">=2.3.1 <3.0.0"
  crypto: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^6.1.0
  build_runner: ^2.11.1
  json_serializable: ^6.13.0
  test: ^1.25.6